apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gw.fullname" . }}-config
  labels:
    {{- include "api-gw.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{ .Files.Get "files/nginx.conf" | indent 4 }}
  log_format.conf: |-
{{ .Files.Get "files/log_format.conf" | indent 4 }}
  app_logger.lua: |-
{{ .Files.Get "files/app_logger.lua" | indent 4 }}
  app_logger_body.lua: |-
{{ .Files.Get "files/app_logger_body.lua" | indent 4 }}
  routes.conf: |-
{{ .Files.Get "files/routes.conf" | indent 4 }}
