version: '3.8'

services:
  nginx:
    image: openresty/openresty:alpine
    environment:
      APP_LOG_INCLUDE_HEADERS: "true"
      APP_LOG_INCLUDE_BODY: "false"
      APP_LOG_HEADER_PARAM: "x-app-header"
    volumes:
      # Mount the configuration directly into OpenResty's default path
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/log_format.conf:/usr/local/openresty/nginx/conf/log_format.conf:ro
      - ./nginx/app_logger.lua:/usr/local/openresty/nginx/conf/app_logger.lua:ro
      - ./nginx/app_logger_body.lua:/usr/local/openresty/nginx/conf/app_logger_body.lua:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - app_network
    # Nincs depends_on, az Nginx rugalmas a resolver miatt.

#  java-client:
#    build: ./java-client
#    restart: always
#    ports:
#      - "8081:8081" # Külső kérés erre a portra jön (böngészőből)
#      # A host gép 80-as portját képezi le a konténer 8081-es portjára.
#    networks:
#      - app_network
#    environment:
#      SERVER_PORT: 8081 # A kliens alkalmazás portja
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s

#  java-backend:
#    build: ./java-backend
#    restart: always
#    ports:
#      - "8082:8082" # Külső kérés erre a portra jön (böngészőből)
#    networks:
#      - app_network
#    environment:
#      SERVER_PORT: 8082 # A backend alkalmazás portja
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s

#  java-backend2:
#    build: ./java-backend2
#    restart: always
#    ports:
#      - "8083:8083"
#    networks:
#      - app_network
#    environment:
#      SERVER_PORT: 8083
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s

networks:
  app_network:
    driver: bridge